### ISSUE TITLE
Send() fails with "The parameter is incorrect error 

### ISSUE THREAD

**Issue by rahulatjet** [clmul/go-windivert#2]
Hi,
I'm trying to call windivert from golang, and found this library which simple, and straightforward to use. The problem I am facing though, is Recv() works but Send() doesn't work. I'm trying to mirror "passthru" example with your library. Here's the code:
``

**Comment by clmul** [comment]
Please post the code.

**Comment by rahulatjet** [comment]
@clmul thanks for the response. Sorry, for the confusion, but I didnt mean to post the issue. I thought this would just be saved as draft. Anyway the code I was trying to run was:
`
func main() {
	handle, err := Open("true", LayerNetwork, 0, 0)
	if err != nil {
		log.Fatal(err)
	}
	defer func() {
		err = handle.Close()
		if err != nil {
			log.Fatal(err)
		}
	}()

	for i:=0; true; i++ {
		packet := make([]byte, 65535)
		n, adrs, err := handle.Recv(packet)
		if err != nil {
			log.Fatal(err)
		}

		_, err = handle.Send(packet[0:n], adrs)
		if err != nil {
			log.Fatal(err)
		}
	}
}
`
So, when i try to send packet entirely instead of packet[0:n], I got the error message: "parameter is incorrect".

Closing the issue.
